// File generated by manual configuration from google-services.json
// Project: push--notification-f5746

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  /// Returns Android FirebaseOptions on Android, throws on Web.
  /// This app only supports Firebase on Android — Web uses Supabase only.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Firebase is not supported on Web in this app. '
        'Build and run on an Android device/emulator instead.',
      );
    }
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJIDFukI9XntXXcEJ4_EUyFT39g-wmrBA',
    appId: '1:736340389126:android:1fd6715f1e9f6054f68287',
    messagingSenderId: '736340389126',
    projectId: 'push--notification-f5746',
    storageBucket: 'push--notification-f5746.firebasestorage.app',
  );

  // iOS not configured yet — uncomment after adding iOS app in Firebase console
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: '',
  //   appId: '',
  //   messagingSenderId: '736340389126',
  //   projectId: 'push--notification-f5746',
  //   storageBucket: 'push--notification-f5746.firebasestorage.app',
  //   iosClientId: '',
  //   iosBundleId: 'com.cst.cst_portal',
  // );
}
